apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: continuous-java-kubernetes
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: io.github.sample/spring-boot-jib
      jib:
        project: spring-boot-jib
        type: maven
        args:
          - -Psync
      context: .
      sync:
        auto: {}
deploy:
  kubeContext: docker-for-desktop
  helm:
    releases:
      - name: spring-boot-jib
        chartPath: spring-boot-jib/src/main/helm
        namespace: default
        valuesFiles:
          - spring-boot-jib/src/main/helm/values-local.yaml
        artifactOverrides:
          image: io.github.sample/spring-boot-jib
        imageStrategy:
          helm: {}    #  	image configuration uses the syntax IMAGE-NAME.repository=IMAGE-REPOSITORY, IMAGE-NAME.tag=IMAGE-TAG.