apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: continuous-java-kubernetes
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: com.github.main/spring-boot-jib
      jib:
        type: maven
      context: .
      sync:
        auto: {}
deploy:
  kubeContext: docker-for-desktop
  helm:
    releases:
      - name: spring-boot-jib
        chartPath: helm
        namespace: default
        valuesFiles:
          - helm/values.local.yaml
        setValueTemplates:
          "image.repository": '{{.IMAGE_NAME}}'
          "image.tag": '{{.DIGEST_HEX}}'