apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: continuous-java-kubernetes
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: io.github.sample/spring-boot-jib
      jib:
        project: spring-boot-jib
        type: maven
      context: .
#      sync:
#        auto: {}
deploy:
  kubeContext: docker-for-desktop
  helm:
    releases:
      - name: spring-boot-jib
        chartPath: spring-boot-jib/src/main/helm
        namespace: default
        valuesFiles:
          - spring-boot-jib/src/main/helm/values.local.yaml
        setValueTemplates:
          "image.repository": '{{.IMAGE_NAME}}'
          "image.tag": '{{.DIGEST_HEX}}'