apiVersion: skaffold/v1beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: com.github.pozo/spring-boot-jib
      jibGradle: {}
     # jibMaven: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml